services:
  postgres-meeting-microservice:
    container_name: postgres-meeting-microservice
    image: postgres:16.3-alpine
    restart: "no"
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INNER_PORT}"
    volumes:
      - postgres_meeting_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - meeting_network
    env_file:
      - .env

  liquibase-meeting-microservice:
    container_name: liquibase-meeting-microservice
    image: liquibase/liquibase:4.31-alpine
    command: liquibase update --url=jdbc:postgresql://postgres-meeting-microservice:${POSTGRES_INNER_PORT}/${POSTGRES_DB} --username=${POSTGRES_USER} --password=${POSTGRES_PASSWORD} --changelog-file=/migrations/db.changeLog-master.yaml
    volumes:
      - ../liquibase/changelog/:/liquibase/migrations/
    networks:
      - meeting_network
    depends_on:
      postgres-meeting-microservice:
        condition: service_healthy

volumes:
  postgres_meeting_data:

networks:
  meeting_network:
  microservice_network:
    external: true