server:
  port: 8081
spring:
  config:
    import: "file:.env[.properties]"
  application:
    name: veloxa-user-microservice
  datasource:
    url: ${DATABASE_FOR_APPLICATION_NOT_IN_DOCKER_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
#logging:
#  level:
#    org.apache.coyote.http11: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka